### ISSUE TITLE
Categorisation of questions for project creation

### ISSUE THREAD

**Issue by cagdasdavulcu** [pnp/generator-teams#109]
As you can see in the screenshot, there is a few questions to be answered. Sometimes is it not transparent which question is for which component:
<img width="1081" alt="Screen Shot 2020-03-08 at 23 20 05" src="https://user-images.githubusercontent.com/1059729/76172180-7046db00-6193-11ea-9070-bfeab2377e4b.png">

Do you think, that can improve the usability of the generator?

**Comment by wictorwilen** [comment]
This is a good idea. The questions are in order, based on the set of components you choose to add, but it could be more clearly explained.

**Comment by appieschot** [comment]
What if we would prefix the questions with for each generator with [generator name]

That would result in something like this: 

- [solution] What is your solution name? 
- [tab] Default Tab name? (1max 16 chars)
- [bot] etc.
- [custombot]
- [connector]
- [extension]
- [localization]

It would be a fairly simple solution and might provide some clarity when filling in the form.

**Comment by RickVanRousselt** [comment]
Good idea, and a more extended version of each question should be in the docs. They appear to be fairly straightforward if you have done Teams dev but if you are just starting out these questions are a bombshell.

So I would reference the docs page link that contains the explanation for each question when the generator starts so that it's easy to find where you can find more information

**Comment by appieschot** [comment]
Closed with 3.4.0-preview
