### ISSUE TITLE
Teams generator using react

### ISSUE THREAD

**Issue by KaushalKhamar** [pnp/generator-teams#135]
Can we have an option to create a solution using React instead of TypeScript?

**Comment by symbiotic** [comment]
i don't understand this question
- React is a GUI framework
- TypeScript is a programming language

what are you trying to do?

**Comment by wictorwilen** [comment]
@KaushalKhamar - as @symbiotic says React and TypeScript are a framework vs a language.

However I guess your question is "create a solution using JavaScript instead of TypeScript". We have no plans on a JavaScript only version of the generator. **But** since TypeScript is a superset of JavaScript you are free to write pure JavaScript as it fits you.
