### ISSUE TITLE
Connecting multiple tabs and a bot, what's the flow?

### ISSUE THREAD

**Issue by aLx450** [pnp/generator-teams#143]
Hi,
I never post on repos so I don't even know if this is appropriate, but the Microsoft Docs are, let's say, less than optimal.

I have been watching YT videos and reading for days now. YO Teams videos are great, but they always show one feature at a time. How does one go about having a complex, multi-tab app? I looked at available apps and it looks so simple... GitHub has multiple tabs, Jira does too. You login, you have access to everything, etc.

I've managed to get a React app with routing into a single tab and a bot, but that's not what I want.
Multiple tabs, in the case of yo-teams, seem to require a .ts page for every tab, which makes sense, but how do you link between these components?

Click a button in Tab A triggers a behind the scenes API call that populates Tab B, etc.
Also, I use Amplify Auth from AWS and in the case of a basic React app, all I have to do is wrap the App component, but there is no top level component in the yo-teams project. Is there something I'm missing?

I know this feels like a StackOverflow question, but I've run out of places to ask. If you have a link to an actual tutorial that does the whole process, I'd take it, for sure.

Thank you!

**Comment by wictorwilen** [comment]
Hi @aLx450 - good question and great to see you comment here. First of all - this gives me some great ideas for additional videos and content to produce around this, thanks.
Secondly - an extension in Teams (tab, bot...) are all its own entities. Of course you can have them all hosted in the same solution and use the same overall configuration. But in order to have them "speak" to each other you need to implement some kind of webservices/API's. For navigation between tabs and bots you use the concept in Teams called *Deep Links*. Deep links allows you to specify an app id and entity id to navigate to.

**Comment by wictorwilen** [comment]
Closing due to no response. Feel free to open again.
