### ISSUE TITLE
Error after scaffolding Action Based Messaging Extension

### ISSUE THREAD

**Issue by sandeepvootoori** [pnp/generator-teams#150]
**Describe the bug**
Created a new action based messaging extension and getting TSLint errors for @types\babel_traverse

**To Reproduce**
1. Create a new action based messaging extension using yo teams 
2. Run gulp serve

**Screenshots**
![image](https://user-images.githubusercontent.com/40895430/93666616-893b1d80-fa4d-11ea-9b9a-3cf35ea9b4c4.png)

**Detailed information**
 - Generator version: [2.15.0]
 - OS: [Windows 10]
 - Node version: [v10.22.0]
 - Npm version: [6.14.5]

**Comment by sandeepvootoori** [comment]
Just tried updating my Node version to latest LTS - v12.18.4 and still facing the same issue

**Comment by Degerada** [comment]
I can confirm the same issue. 
It is tied to jest.
Once you remove the jest-related dependencies from the projects, babel__traverse won't be used by the project anymore and it will build successfully.

I do not know what's causing this issue, because I have other projects with jest that compile fine, but this serves as a workaround.

As for cause investigation, I tried building this project with:
npm 6.14.8
Manjaro Linux latest
NodeJS 10, 12 and 14
Generator version 2.15 and 2.16 preview.

switching the NodeJS and Generator versions around didn't resolve anything, issue exists with all combinations.

**Comment by sandeepvootoori** [comment]
I will give it a try until this is fixed

**Comment by sandeepvootoori** [comment]
> I can confirm the same issue. 
> 
> It is tied to jest.
> 
> Once you remove the jest-related dependencies from the projects, babel__traverse won't be used by the project anymore and it will build successfully.
> 
> 
> 
> I do not know what's causing this issue, because I have other projects with jest that compile fine, but this serves as a workaround.
> 
> 
> 
> As for cause investigation, I tried building this project with:
> 
> npm 6.14.8
> 
> Manjaro Linux latest
> 
> NodeJS 10, 12 and 14
> 
> Generator version 2.15 and 2.16 preview.
> 
> 
> 
> switching the NodeJS and Generator versions around didn't resolve anything, issue exists with all combinations.

I will give it a try, Thanks for testing

**Comment by wictorwilen** [comment]
See #154
