### ISSUE TITLE
Deploy to Azure using Azure Extension - Throwing error

### ISSUE THREAD

**Issue by NWH-SAmin5** [pnp/generator-teams#157]
Deploying the solution throws error. Somehow after successful deployment site is not able to browse to Tab html pages. Need to update Virtual Directory location to dist\web folder. It works after point virtual directory to dist\web folder.
But at this point Bot endpoint api\messages comes as Not Found 404.

**Is your feature request related to a problem? Please describe.**
The problem is, after generator creates the solution. Using Azure Extension, deploying to Azure App Service throws error.

**Describe the solution you'd like**
Documentation for exact steps to deploy to Azure Web App

**Describe alternatives you've considered**
I have tried following these links
[microsoft docs for nodejs deploy on azure](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial-vscode-azure-app-service-node-03)
[bot deploy to azure](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=typescript)

**Comment by wictorwilen** [comment]
Hi, please avoid using the direct Git deployment and use a solution like zip deployment from Azure DevOps (https://www.wictorwilen.se/blog/deploying-yo-teams-and-node-apps/) or through Azure CLI (https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest).

We've even removed the default git deployment files and instructions from the latest release, due to quite a few issues with it.
