### ISSUE TITLE
Unable to debug with Yo Teams 2.16 + Having better docs?

### ISSUE THREAD

**Issue by Marc93-14** [pnp/generator-teams#221]
Steps in the docs aren't clear on how to debug apps with Yo Teams. 

I don't currently have launch.json, when I create one which type do I choose? NodeJS? Nodejs legacy?

I chose any type then copied pasted the code provided by README file, now I run gulp ngrok-serve --debug .. that doesn't do anything. Do I need to click F5 then to start debugging?

The steps in the readme aren't really complete, it just says run gulp serve --debug which doesn't run the ngrok process. Is there any decent documentation on how to configure debugging for yo teams?

**Note**
Also, I don't find any good docs for Yo Teams, the docs send me to Microsoft docs for teams development, there it sends me again to the yo teams repo which has like 5 simple walkthroughs and that's it. Is there a detailed documentation for how to use it, explanation of the methods inside etc. I find it very hard to learn Teams development with just the resources available that sends me back and forth between MS teams docs and this repo.

**Comment by wictorwilen** [comment]
Hi @Marc93-14. The easiest way to get debugging to work is to 
1) Create a `.vscode/launch.json` file 
2) Add the following to the file:
``` json
 {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "outFiles": ["${workspaceFolder}/dist/**/*.js"]
        }
```
3) Start your application with `gulp serve --debug` or `gulp ngrok-serve --debug` (since that's what you mentioned)
4) Go to the debug extension in VSCode and start the Debug task you just added, select the correct node process and debug away

Re documentation: there are some work going on here with the official docs, and we're always looking for improvements to the documentation. As this is a community driven effort, we are open to suggestions for new content as well as more than gladly accept PR's with documentation updates.

**Some backstory**: we have deliberately not added any environment specific configuration such as launch.json. This is something that will change in the upcoming release (3.2+)

**Comment by Marc93-14** [comment]
Thank you @wictorwilen when I try itI get this error: 
Error processing attach: Error: Could not connect to debug target at http://localhost:5858: Promise was canceled at Object.e[as retryGetWSEndpoint]

This error is when I hit F5 (or go to debug tab, click start and choose my process).

**Comment by wictorwilen** [comment]
@Marc93-14 - just tested on a fresh scaffolded project with this setup, try if that works:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "attach",
            "name": "Attach to server",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "restart": true
        }
    ]
}
```

(This is what will end up in the upcoming versions)

**Comment by Marc93-14** [comment]
@wictorwilen that worked! 
For the documentation, the Microsoft learn is still using yo teams v 2.16, and the Microsoft videos are being done on the same version by someone who is just reading the same microsoft learn material. i was expecting the microsoft videos to have some details or a bit different from the microsoft learn site. How are we supposed to learn the yo teams, or teams in general if the docs aren't detailed? all i find is random blog posts by smart people in the community in order to learn from. I

i would like to contribute if I can, but if we don't understand the tool itself how can we?
