### ISSUE TITLE
Add Azure AD SSO support to Tabs

### ISSUE THREAD

**Issue by wictorwilen** [pnp/generator-teams#59]
**Is your feature request related to a problem? Please describe.**
Add Azure AD SSO support to Tabs

**Describe the solution you'd like**
A great SSO experience for end-users

**Comment by cagdasdavulcu** [comment]
@wictorwilen will this feature be based on this documentation or do you have any other idea? 
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso

**Comment by wictorwilen** [comment]
@cagdasdavulcu - yes, that is what we should implement

**Comment by AhmadiRamin** [comment]
Hi Guys,

I'm getting this error when I try to run the project using ngrok-serve:

An SSO error occurred App resource defined in manifest and iframe origin do not match

is it related to this?

I couldn't find any documentation regarding the ngrock parameters in env file, should I leave them blank? how does it work?

[Here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso) it says "We also do not support applications that use the azurewebsites.net domain since this domain is too common and may be a security risk"

So I'm wondering if it is not supported, why we need to deploy the package to azure app service?

I appreciate if someone give me a hint how I can deploy/debug it without SSO error.

**Comment by wictorwilen** [comment]
@AhmadiRamin - since you're using `ngrok-serve` you need to configure your app-uri to match that ngrok address.

**Comment by wictorwilen** [comment]
Added in version `1.13.0`

**Comment by atomroflman** [comment]
@wictorwilen I generated a new teams app using: https://docs.microsoft.com/de-de/microsoftteams/platform/tutorials/get-started-yeoman
Then I tried to change the 'MYAPP_APP_URI=' paramter in the environment file. To my latest ngrok address 'id12345.ngrok.io' anyways it tells me 'An SSO error occurred App resource defined in manifest and iframe origin do not match'.
So I guess you didn't mean to reconfigure this attribute. Can you give additional information where to change the configuration to get the `ngrok-serve` running?

**Comment by wictorwilen** [comment]
@atomroflman - ensure that you use the same host name in the Azure AD app registration an in the .env file. Remember that the ngrok Url changes everytime you start "gulp ngrok-serve", which means that you must update everything as well as reupload the app to Teams.
I do not recommend this approach for SSO Tabs, and either recommend reserving domains in ngrok (costs a small fee) or use a custom do in of your own.
